### PR TITLE
Fix Win32/SDL Mouse Capture Anomalies

### LINKED ISSUE #1828: Mouse Capture Anomalies
This is a continuation of #1823 to address minor anomalies that still exist between ENIGMA and GM with regards to mouse behavior. What ENIGMA did in #1825 and #1824 was correct and an improvement. However, it's not exactly like GM since the capture can be prematurely released by press-and-releasing a different mouse button than the one that started the capture.

The problem here is that GM8.1 not only captures the mouse when a button is pressed inside the window, it seems to also record which button was pressed. From testing, I am able to show that it's possible to get GM8.1's mouse state stuck just like you can ENIGMA's. If we use the below draw code, we can actually press-and-move the left mouse button outside the window, which captures the mouse. Then we can press-and-hold the right mouse button and finally release the left button. GM8.1 at that point releases the mouse capture and if we release the right mouse button outside the window then, GM8.1 thinks it is still activated!

```gml
draw_text(0,0,string(mouse_check_button(mb_left)) + " " +
              string(mouse_check_button_pressed(mb_left)) + " " +
              string(mouse_check_button_released(mb_left)) + "#" +
              string(mouse_check_button(mb_right)) + " " +
              string(mouse_check_button_pressed(mb_right)) + " " +
              string(mouse_check_button_released(mb_right)) + "#" +
              string(keyboard_check(vk_space)) + " " +
              string(keyboard_check_pressed(vk_space)) + " " +
              string(keyboard_check_released(vk_space)));
```

This is **_NOT_** reproducible in GMSv1.4 and the issue seems to have been fixed!

I don't actually see this as an issue that we necessarily need to do anything about, but GMSv1.4 suggests YoYo did something about it. I think we could go years without anybody ever having a problem, but it is possible for us to easily adopt what GM8.1 does. However, since GM8.1 is also busted, I have my own proposal, which is that we just hold the mouse capture until **_ALL_** mouse buttons are released. We could also just read the mouse state directly.

### PR DESCRIPTION
**Pull request by RobertBColton**
Alright, I did it, I figured out how to fix #1828 correctly. Initial guesses that all mouse buttons need to be released for the mouse capture to be released are correct. The problem was I didn't want to call out to any other API, but then I realized all of the UP mouse input messages have a wParam which tells us the state of the other mouse buttons. Clearly it tells us whether all mouse buttons have been released!

With these changes the mouse capture works perfectly, the same as GMSv1.4, and other applications as it is expected to work. The mouse is correctly captured now and mouse releases are always properly detected inside and outside of the window.

What's funny is other people haven't figured out the wParam trick, and I notice several people using integers counters and other weird tricks. SDL video API is an example of this where they seem to be holding a counter variable of how many mouse buttons are pressed, though I do suppose that could have other uses. What's interesting is that this does not apply to SDL windowing API, which I still have to patch here, because it lets you control the mouse capture.
http://hg.libsdl.org/SDL/diff/1b87a8beab9d/src/video/win32/SDL_win32events.c

SFML is at least smart enough to check the wParam like me, but they check all of the modifiers individually.
https://github.com/SFML/SFML/pull/457/files

freeglut was also patched in the same way, though they use the async key polling in the place of wParam.
https://sourceforge.net/p/freeglut/mailman/message/30537813/
```cpp
         else if (!GetAsyncKeyState(VK_LBUTTON) && !GetAsyncKeyState(VK_MBUTTON) && !GetAsyncKeyState(VK_RBUTTON))
           /* Make sure all mouse buttons are released before releasing capture */
           ReleaseCapture () ;
```

Edit: There is no need to fix Cocoa here, because I read in online Stackoverflow posts as well as comments in the SDL source where the Cocoa backend has only a stub for capture, that Cocoa automatically handles mouse capture for mouse events.

### CODE REVIEW

File: ENIGMAsystem/SHELL/Platforms/SDL/Event.cpp [hunk 1]
```diff
@@ -135,8 +135,8 @@ int SDL_Event_Handler::processEvents() {
 int SDL_map_button_enum(const char button) {
   switch (button) {
     case SDL_BUTTON_LEFT: return 0;
-    case SDL_BUTTON_MIDDLE: return 1;
-    case SDL_BUTTON_RIGHT: return 2;
+    case SDL_BUTTON_RIGHT: return 1;
+    case SDL_BUTTON_MIDDLE: return 2;
```
Comment (RobertBColton) [inline ENIGMAsystem/SHELL/Platforms/SDL/Event.cpp:139]: I also fixed the SDL mouse button mapping while I was in here, it had right and middle mapped backwards.

File: ENIGMAsystem/SHELL/Platforms/SDL/Event.cpp [hunk 2]
```diff
@@ -253,7 +253,6 @@ void SDL_Event_Handler::mouseButtonDown(const SDL_Event *event) {
 void SDL_Event_Handler::mouseButtonUp(const SDL_Event *event) {
   int btn = SDL_map_button_enum(event->button.button);
   if (btn < 0) return;
-  SDL_CaptureMouse(SDL_FALSE);
```
Comment (RobertBColton) [inline ENIGMAsystem/SHELL/Platforms/SDL/Event.cpp:256]: Apparently, we do not need to explicitly tell SDL to end mouse capture. It already tracks in its Windows video backend the count of mouse buttons that are pressed, and automatically revokes the mouse capture when all the mouse buttons are released. Simply having this line is what caused SDL to have the anomaly to begin with.

Comment (RobertBColton) [reply ENIGMAsystem/SHELL/Platforms/SDL/Event.cpp:256]: It would be particularly shitty if I have to come back and change this for xlib later or something because SDL does not provide a wParam equivalent for its mouse events, despite using those same modifiers internally. You would have to request the entire mouse state.

**Comment by RobertBColton** [comment]
@time-killer-games Can you test this using Win32 and SDL platforms and the SDL version on xlib? The goal is detecting mouse releases outside of the game window as GMS does. I would also like to know what the SDL version behaved like on xlib _before_ this change too.

**Comment by fundies** [comment]
I will test if you got a gmk handy

**Comment by RobertBColton** [comment]
Here's one, I didn't post it because it's just a draw code I put in #1828. First line is left mouse button, second is right, and last is spacebar on keyboard.

Download: [mouse-capture-test.zip](https://github.com/enigma-dev/enigma-dev/files/4827796/mouse-capture-test.zip)

**Comment by RobertBColton** [comment]
You just click, with any mouse button on the window, hold outside window, press a second button, and release the original. Ensure all press and releases are correct. Be aware there's a difference in starting the capture with left vs right button, because GM8.1 only ever recognized the left button as a result of copying Microsoft's shoddy examples. There's also a difference between starting with left, press and release right, then releasing left and starting with left, pressing right, releasing left, then releasing right.

**Comment by fundies** [comment]
On master I just get ```USER_ERROR: in some action of some event for object 0, instance id 100001: Cannot access font with id -1 | Graphics_Systems/General/GSfont.cpp:362```

I tried adding a font in to no effect.

**Comment by RobertBColton** [comment]
Uhm, that doesn't sound right, you sent a fix for that when I had it, remember? I just created this branch, so it's not possible to be older than that fix either.

**Comment by fundies** [comment]
> Uhm, that doesn't sound right, you sent a fix for that when I had it, remember? I just created this branch, so it's not possible to be older than that fix either.

This is master. I haven't tested your branch yet. I dunno If my fix was ever merged.

**Comment by RobertBColton** [comment]
Yeah I think it was then you probably just need to git pull or make clean or something similar.

**Comment by fundies** [comment]
> Yeah I think it was then you probably just need to git pull or make clean or something similar.

This is a fresh clone. I'm up to date

**Comment by RobertBColton** [comment]
Oh, it needs to draw but has no font. You added a font, then did you try adding draw_set_font before my draw_text?

**Comment by fundies** [comment]
> Oh, it needs to draw but has no font. You added a font, then did you try adding draw_set_font before my draw_text?

Setting font works but there should be a default font at index -1 so somethings going wrong there

**Comment by RobertBColton** [comment]
Yeah definitely because for me on Windows, I pulled your fix when you had it, and the default font is working.

**Comment by fundies** [comment]
Ok, so xlib was fine on master. I see the issue in SDL. While your fix does make it register the clicks outside the window correctly they are also lost and I am unable to click other windows and cannot close the game without alt-tabbing

**Comment by RobertBColton** [comment]
That's really sad, but ok, I know how to fix it then, just revert to master and change it like Win32, to check that all mouse buttons are released. Damn it SDL! How could they get Windows right but screw up X11! They were so close!

**Comment by RobertBColton** [comment]
@fundies ENIGMAsystem/SHELL/Platforms/SDL/Event.cpp

Can you try
`if (!event->button.button) SDL_CaptureMouse(SDL_FALSE);`
And
`if (!event->button.state) SDL_CaptureMouse(SDL_FALSE);`
Without and without the negation.

**Comment by RobertBColton** [comment]
Hrm, I don't think that will work because if it was a bitmask, then the docs would say like they do for mouse motion events.
https://wiki.libsdl.org/SDL_MouseMotionEvent#Remarks

SDL is so silly.

**Comment by RobertBColton** [comment]
I just committed the version that I know works for sure, but was avoiding because of the possibility it's doing more work than I want. You can still test those other ones though to see, I am not able to because Windows is automatically fixing the capture for me biasing the results over here.

File: ENIGMAsystem/SHELL/Platforms/SDL/Event.cpp [hunk 3]
```diff
@@ -253,7 +253,7 @@ void SDL_Event_Handler::mouseButtonDown(const SDL_Event *event) {
...
+  if (!SDL_GetMouseState(NULL, NULL)) SDL_CaptureMouse(SDL_FALSE);
```
Comment (RobertBColton) [inline ENIGMAsystem/SHELL/Platforms/SDL/Event.cpp:256]: Well, at least I can say by looking at the source, this does seem to be cached, so not really that much different from wParam I guess.
https://github.com/spurious/SDL-mirror/blob/3384f7b2845eeeae887386d0879a24d066678775/src/events/SDL_mouse.c#L172
https://github.com/spurious/SDL-mirror/blob/3384f7b2845eeeae887386d0879a24d066678775/src/events/SDL_mouse.c#L702

**Comment by fundies** [comment]
Well whatever you committed seems good

**Comment by RobertBColton** [comment]
Awesome, thanks, now I can add multitouch support to SDL which will work on Android. I am simulating multitouch in Windows using multiple mice (something you can do and is built into SDL).

**Comment by fundies** [comment]
> Awesome, thanks, now I can add multitouch support to SDL which will work on Android. I am simulating multitouch in Windows using multiple mice (something you can do and is built into SDL).

Well if you want android to work you'll need to fix / merge #1903

**Comment by RobertBColton** [comment]
Also, wow, so this is quite funny. I just got done setting up Ubuntu 20 in VirtualBox and installing fresh enigma-dev from the Wiki (I didn't hit your font issue?) so I can test multitouch later. Anyway, I noticed that both xlib and SDL are fine with detecting the mouse release outside the Window. I was able to reproduce your window freeze as a result of capturing the mouse too long. But @fundies can I ask what Window manager you were using and if you could still test just regular old xlib platform too?

This sucks the way this turned out that because xlib and Windows were both equally screwed up in the SDL implementation we have to have the full blown thing, which is basically like just managing the capture ourselves. This is why abstract windowing libraries aren't always great when it comes down to working around platform inconsistencies.

**Comment by RobertBColton** [comment]
And yeah, I can now double confirm the other solutions than `SDL_GetMouseState` do not work.

**Comment by fundies** [comment]
I am using cinnamon DE right now but I doubt its any different for any other DE

**Comment by RobertBColton** [comment]
Interesting, looks like ENIGMA might be using a special hint which changes into active input mode that automatically handles the capture. Cocoa being Linux/Unix inspired and even supporting xlib in the past could be the reason Cocoa supposedly does the same as I read online.

**Comment by time-killer-games** [comment]
I will be busy for the next couple of days but I'll let you know my results after I have tested it if you still need me by then.

**Comment by RobertBColton** [comment]
Thanks, I think we're good on this one now though, very sure of the correctness of the change now. Though you are still needed in some other places and pull requests.
