### PR TITLE
Fix Data Structure Shuffle Functions

### LINKED ISSUE #1107: Randomize is not connect with ds_list_shuffle
Hello.

The GMS Randomize affects the values created by ds_list_shuffle (they are random). Enigma randomize does not affect them. We always get the same value.

Example (if you have GMS and Enigma):
http://meshnet-users.tk/paste/p/homh/a.gmk

### PR DESCRIPTION
**Pull request by RobertBColton**
This pull request attempts to resolve #1107 

> ds_grid_shuffle(id) Shuffles the values in the grid such that they end up in a random order.
> ds_list_shuffle(id) Shuffles the values in the list such that they end up in a random order.

The data structure shuffle functions should be connected to the user random functions such that a user specified seed or randomize call will affect the order.
https://docs.yoyogames.com/source/dadiospice/002_reference/data%20structures/ds%20lists/ds_list_shuffle.html
https://docs.yoyogames.com/source/dadiospice/002_reference/data%20structures/ds%20grids/ds_grid_shuffle.html
> NOTE: This function will shuffle the list items to the same positions every time the game is run afresh due to the fact that GameMaker: Studio generates the same initial random seed every time to make debugging code a far easier task. To avoid this behaviour use randomize at the start of your game. This is only true when testing and debugging the game, as the final executable package will not show this behaviour and will be random every play.

I've updated our documentation accordingly:
https://enigma-dev.org/docs/Wiki/Ds_list_shuffle
https://enigma-dev.org/docs/Wiki/Ds_grid_shuffle

There are only two problems with this pull request right now:
1) We are cock-blocking include `mathnc.h` outside of SHELL main, so I had to redeclare/redefine some of the enigma_user functions.
2) The `enigma_user::irandom` function is inclusive, so it can't be used directly. Should I just make a custom random just for this source that is not inclusive?

### CODE REVIEW

File: ENIGMAsystem/SHELL/Universal_System/Extensions/DataStructures/data_structures.cpp [hunk 1]
```diff
@@ -52,6 +54,16 @@ template<typename t> bool tequal(t v1, t v2) { return v1 == v2; }
 template<> bool tequal(float v1, float v2)   { return fequal(v1, v2); }
 template<> bool tequal(double v1, double v2) { return fequal(v1, v2); }
 
+namespace enigma_user {
+  // why the fuck can't we just include mathnc.h here?
+  // for connecting ds_list_shuffle and ds_grid_shuffle
+  // to randomize as specified by GM docs
+  extern ma_scalar random(ma_scalar n);
+  static inline int random_integer(int x) {
```
Comment (JoshDreamland) [inline ENIGMAsystem/SHELL/Universal_System/Extensions/DataStructures/data_structures.cpp]: Doesn't this function exist? Anyway, don't declare this in `enigma_user`, even if it's static.

Comment (RobertBColton) [reply ENIGMAsystem/SHELL/Universal_System/Extensions/DataStructures/data_structures.cpp]: Yes, HOWEVER:

1) It's inclusive which doesn't work with random_shuffle:
https://github.com/enigma-dev/enigma-dev/blob/edccdb82110f545ec7051e48b9df80ce1a2c5c50/ENIGMAsystem/SHELL/Universal_System/mathnc.h#L220
2) I am not allowed to include `mathnc.h`:
https://github.com/enigma-dev/enigma-dev/blob/edccdb82110f545ec7051e48b9df80ce1a2c5c50/ENIGMAsystem/SHELL/Universal_System/mathnc.h#L41

Comment (JoshDreamland) [reply ENIGMAsystem/SHELL/Universal_System/Extensions/DataStructures/data_structures.cpp]: I see... that is kind of sad. But all the function does is cast the result of `random`, so why not just cast the result of random.

Also, feel free to extract the `random` family of functions into a separate header. I forbade including `mathnc` outside of the SHELLmain because polygone kept using it for GM's math functions instead of just using the C++ equivalents.

Comment (RobertBColton) [reply ENIGMAsystem/SHELL/Universal_System/Extensions/DataStructures/data_structures.cpp]: Alright, I've tweaked it: 45089f939b72cfd70ca6490b53eff47771afa7fe

I moved all the random stuff to `Universal_System/mathrand.h` which allows me to include elsewhere. I also used the random generator for `random_shuffle` to namespace enigma and out of enigma_user.

It appears to continue working and shuffling the list correctly.

**Comment by RobertBColton** [comment]
Alright, after thinking about your comments, I decided to split apart `random.h` and `random.cpp` from `mathnc.h` and `mathnc.cpp`: b40e97cb1361500b4de83af9ec57bb987891cb45

I made this decision because the way I had it organized before is not really how we've done it anywhere else in ENIGMA. I feel that it's confusing to only separate a few functions into a separate header and use the same source for implementation. I still do this for things like `GSvertex_impl.h` but I feel that is much clearer because it's understood that I am trying to keep it from polluting the global namespace.

Having said all of that, I am now going to squash merge this.
