### PR TITLE
Fix Empty Keyboard String Crashes

### LINKED ISSUE #1743: Empty Keyboard String Backspace Crash
I don't think this is connected with #1437. So, anyway, when I compile an empty game or just a game with a single room on Windows, the produced executable crashes when I attempt to double click it or run it from within the MinGW64 shell.

I was trying to reproduce a backspace issue reported by Darkstar.
https://enigma-dev.org/forums/index.php?topic=2999.msg27586#msg27586

So, what I did instead was compile the GMSv1.4 3D Cubes Demo and that worked. When I open the exe by double clicking, the game opens fine. If I then press backspace, it crashes.

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffd8a1ce912 in ntdll!RtlCallEnclaveReturn ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007ffd8a1ce912 in ntdll!RtlCallEnclaveReturn ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x00007ffd8a13c50f in ntdll!RtlWalkFrameChain ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x00007ffd8a13c48a in ntdll!RtlWalkFrameChain ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#3  0x00007ffd8a13c402 in ntdll!RtlCaptureStackBackTrace ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#4  0x00007ffd8a22c515 in ntdll!RtlpNtSetValueKey ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#5  0x00007ffd8a1ca505 in ntdll!RtlRaiseStatus ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#6  0x00007ffd8a1d9931 in ntdll!memset () from C:\WINDOWS\SYSTEM32\ntdll.dll
#7  0x00007ffd886398bc in msvcrt!free () from C:\WINDOWS\System32\msvcrt.dll
#8  0x0000000000417bbb in ?? ()
#9  0x0000000000000102 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

### PR DESCRIPTION
**Pull request by RobertBColton**
This pull request fixes #1743 for Darkstar. Basically, we just needed to add a check if the `keyboard_string` was not empty before trying to remove a character from it. SDL did not have this problem as it seems it's already making that check. I am not bothering to add input tests right now, we can do that later. Let's just fix the crash for Darkstar right now. I confirm it fixed the crash for me and `keyboard_string` continues working just fine.

### CODE REVIEW

File: ENIGMAsystem/SHELL/Platforms/Win32/WINDOWScallback.cpp [hunk 1]
```diff
@@ -36,10 +35,6 @@ using std::map;
 #endif
 
 namespace enigma_user {
-extern int keyboard_key;
-extern int keyboard_lastkey;
-extern string keyboard_lastchar;
-extern string keyboard_string;
```
Comment (RobertBColton) [inline ENIGMAsystem/SHELL/Platforms/Win32/WINDOWScallback.cpp]: For some reason these are split between `PFmain.h` and `PFwindow.h` but regardless, we don't need the extra trash linger around.
