### PR TITLE
fix gmx path background room

### LINKED ISSUE #1871: GMX reader doesn't read the path's "background room" property properly
GMX stores a room's background as an Integer (unlike every other resource reference)
We expect a string in the proto so we need to convert their integer to the room name upon read.

### PR DESCRIPTION
**Pull request by fundies**
fixes #1871

### CODE REVIEW

File: CommandLine/libEGM/gmx.cpp [hunk 1]
```diff
@@ -29,15 +29,16 @@
 #include <vector>
 
 using CppType = google::protobuf::FieldDescriptor::CppType;
+using LookupMap = std::unordered_map<std::string, std::unordered_map<int, std::string>>;
```
Comment (RobertBColton) [inline CommandLine/libEGM/gmx.cpp:32]: Totally unnecessary, it already exists.
https://github.com/enigma-dev/enigma-dev/blob/b0375a3f7f25897f680e9d47dcb517406f82b15c/CommandLine/libEGM/gmx.cpp#L82

File: shared/protos/Path.proto [hunk 2]
```diff
@@ -12,7 +12,7 @@ message Path {
 
   optional int32 id = 2 [(gmx) = "GMX_DEPRECATED"];
 
-  optional string background_room_name = 3 [(resource_ref)="room", (gmx_id) = "backroom"];
+  optional string background_room_name = 3 [(resource_ref)="room", (gmx) = "backroom"];
```
Comment (RobertBColton) [inline shared/protos/Path.proto:15]: The `gmx_id` was unimplemented because it wasn't necessary in the command line. I believe the intention was for `_id` suffix to mean convert the string to an id.

File: CommandLine/libEGM/gmx.cpp (hunk 1 above)
Comment (fundies) [reply CommandLine/libEGM/gmx.cpp:32]: the string in that map is the resource type not the name

File: shared/protos/Path.proto (hunk 2 above)
Comment (fundies) [reply shared/protos/Path.proto:15]: well this is the only field like this in gmx so having an attribute for it doesn't seem necessary

File: CommandLine/libEGM/gmx.cpp (hunk 1 above)
Comment (RobertBColton) [reply CommandLine/libEGM/gmx.cpp:32]: Oh, it's the base id for that resource type. That's how I used it in #1989 to fix instance ids.

File: shared/protos/Path.proto (hunk 2 above)
Comment (RobertBColton) [reply shared/protos/Path.proto:15]: It still looks cleaner, and because of options/texture pages/audio groups that might not be the case. I have not truly seen 100% of the GMX format.

Regardless, this was in fact a mistake by YoYoGames, I am sure. If you create and delete a bunch of rooms, then set the path background room, save and reopen, it can be a different room after reopening. Since GMX doesn't save the ids, they are defragged when the project is reopened.

Nothing we can do about it now though.

File: CommandLine/libEGM/gmx.cpp (hunk 1 above)
Comment (fundies) [reply CommandLine/libEGM/gmx.cpp:32]: it could probably stand to be renamed as I was confused to its purpose as well

Comment (RobertBColton) [reply CommandLine/libEGM/gmx.cpp:32]: Just call it typeBaseId since it's the last id used for each resource. Or call it `maxId` or `maxTypeId` or something.

File: shared/protos/Path.proto (hunk 2 above)
Comment (fundies) [reply shared/protos/Path.proto:15]: right its just a workaround for bug yoyo has in gmx. Every other resource we've seen in gmx uses a string so until another one appears im not interested in using an attribute

File: CommandLine/libEGM/gmx.cpp (hunk 1 above)
Comment (fundies) [reply CommandLine/libEGM/gmx.cpp:32]: I wasn't planning on doing it here but if you want to shoehorn it in I have allow edits from maintainers on

File: shared/protos/Path.proto (hunk 2 above)
Comment (fundies) [reply shared/protos/Path.proto:15]: Well we could have lgm save the room as a string / another attribute to ensure at-least lgm doesn't  de-synced the room name/id but I don't think it's super important

Comment (RobertBColton) [reply shared/protos/Path.proto:15]: Sure, would be interesting to see if GMSv1.4 could read it too.
