### PR TITLE
only pad images in create texture

### LINKED ISSUE #1936: image_load doesn't give good errors
image_load doesn't error when a format isn't supported and instead just runs bmp loader and errors there when it cant read header data. If an image format isn't supported it should give an error message saying so before trying to load it as a bmp.

you can reproduce this by building a game with libpng extension off and trying to load a png using sprite_add or whatever.

### LINKED ISSUE #2000: sprite_add() regression
Here's th PNG I'm trying to load with sprite_add():

m1_1

Here's what it looks like drawn to the game after sprite_add() (stretched to fill game window):

regression

It happens regardless of how you draw it, whether stretched or otherwise.

reproducible gm91 project and png:

[regression.zip](https://github.com/enigma-dev/enigma-dev/files/4561797/regression.zip)

### LINKED ISSUE #2003: Sprite regression for npo2
Because I can't comment on #2000 due to tkg being tkg. I guess I'll make separate issue.
It appears I've broken sprite_add for non power of 2 textures because image_load pads the textures to power of 2 but when I do things like divide the subimages or remove the transparency pixel, my code expects an unmolested image. This only effects externally loaded non-power of 2 images. So we need to either modify image_load not to molest the images or modify my split/transparency functions to take the garbage padding into account.

https://github.com/enigma-dev/enigma-dev/blob/master/ENIGMAsystem/SHELL/Universal_System/Resources/sprites.cpp#L41

### PR DESCRIPTION
**Pull request by fundies**
moved image padding logic exclusively to graphics_create_texture

fixes #2003
fixes #1936 
Currently only png works, need help fixing bmp/gif

### CODE REVIEW

File: ENIGMAsystem/SHELL/Universal_System/Resources/fontinit.cpp [hunk 1]
```diff
@@ -67,8 +67,8 @@ void exe_loadfonts(FILE* exe) {
 
     const unsigned int size = twid * thgt;
 
-    unsigned char* pixels =
-        new unsigned char[size * 4 + 1];  //FYI: This variable was once called "cpixels." When you do compress them, change it back.
+    int* pixels =
+        new int[size + 1];  //FYI: This variable was once called "cpixels." When you do compress them, change it back.
```
Comment (RobertBColton) [inline ENIGMAsystem/SHELL/Universal_System/Resources/fontinit.cpp]: @fundies you had broken fonts here, this fixes them. I would just leave it as int because it simplifies the for loop below it, there is nothing harmful in the later cast. Otherwise you'd have to change the 1 line in the for loop to 4 lines to assign each channel, I think it's nice the way Josh had it.

File: ENIGMAsystem/SHELL/Universal_System/Resources/fontinit.cpp [hunk 2]
```diff
@@ -138,11 +138,10 @@ void exe_loadfonts(FILE* exe) {
     font.height = ymax - ymin + 2;
     font.yoffset = -ymin + 1;
 
-    font.texture = graphics_create_texture(twid, thgt, twid, thgt, pixels, false);
+    font.texture = graphics_create_texture(RawImage((unsigned char*)pixels, twid, thgt), false);
     font.twid = twid;
     font.thgt = thgt;
 
-    delete[] pixels;
```
Comment (RobertBColton) [inline ENIGMAsystem/SHELL/Universal_System/Resources/fontinit.cpp:145]: @fundies This isn't good because the size of `pixels` here was `size + 1` where size may not have been the product of width and height of the texture. Why did you remove so many of these deletes? Did you make RawImage handle the cleanup?

**Comment by RobertBColton** [comment]
With my last commit there to fix the fonts, the space cleaner game works fine on this branch again now.
Space Cleaner Image Pad Branch

File: ENIGMAsystem/SHELL/Universal_System/Resources/fontinit.cpp (hunk 2 above)
Comment (fundies) [reply ENIGMAsystem/SHELL/Universal_System/Resources/fontinit.cpp:145]: Yes RawImage automatically deletes when it goes out of scope in it's destructor

**Comment by fundies** [comment]
> With my last commit there to fix the fonts, the space cleaner game works fine on this branch again now.
> Space Cleaner Image Pad Branch

pngs should be fine in this branch but bmps and gifs are broken. I have a test in this PR you can run to check things.

File: ENIGMAsystem/SHELL/Universal_System/Resources/fontinit.cpp (hunk 2 above)
Comment (RobertBColton) [reply ENIGMAsystem/SHELL/Universal_System/Resources/fontinit.cpp:145]: Hrm, font is tricky edge case then, I wonder what the extra +1 on the size is.

Comment (fundies) [reply ENIGMAsystem/SHELL/Universal_System/Resources/fontinit.cpp:145]: I would rather 3 extra lines than some confusing hack though

**Comment by RobertBColton** [comment]
Ok so 84161d34ba97fee7e1abac17e819acdd9de899b6 fixes the subimages but there's still more problems.

The background transparency is wrong and I'm not sure it was correct to begin with. In GIF the background color should not appear if it equals the subimage's transparent color, but in our implementation it is because we clear the initial buffer to the background color regardless of whether it is the transparent color of the first subimage.

All of "Phase 2" can actually be deleted now because of Josh's refactor we aren't writing them to one giant buffer. When we see a subimage block, we can just allocate the raw image then and push it to the images vector.
