### PR TITLE
Fix Proto2ES Zlib Compression

### LINKED ISSUE #1254: GMK/Emake image loading issues
I tried to run http://files.enigma-dev.org/game/69/file/1/0be4e3/Source/platform_engine.gmk from the edc using emake and I get 

ERROR in some action of some event for object -4, instance id -4: Zerror: Output of 16 above allotted 16
ERROR in some action of some event for object -4, instance id -4: Sprite load error: Sprite does not match expected size

but I can run the same game from lgm fine.

### PR DESCRIPTION
**Pull request by RobertBColton**
This fixes #1254 to the fullest. @JoshDreamland correctly discovered for me that the block size was being written incorrectly. I traced it down to my copy of `zlib_compress` in Proto2ES not returning the outsize with the correct size of the compressed data.

With this one fixed, I have added a new game to my list of emake projects that now work. The platforming engine from the EDC: https://enigma-dev.org/edc/games.php?game=69

Game exhibiting problems: [platform_engine.zip](https://github.com/enigma-dev/enigma-dev/files/2079012/platform_engine.zip)

```
./emake "C:/Users/Owner/Desktop/GMGames/platform_engine.gmk" -o /tmp/test.exe -r -c Precise
```

image

### CODE REVIEW

File: CommandLine/emake/Proto2ES.cpp [hunk 1]
```diff
@@ -237,13 +237,15 @@ std::string Actions2Code(const ::google::protobuf::RepeatedPtrField< buffers::re
 
 #include <zlib.h>
 
-unsigned char* zlib_compress(unsigned char* inbuffer,int actualsize)
+unsigned char* zlib_compress(unsigned char* inbuffer,int &actualsize)
 {
     uLongf outsize=(int)(actualsize*1.1)+12;
```
Comment (JoshDreamland) [inline CommandLine/emake/Proto2ES.cpp]: So this is what you were referring to. This was because, if you pass zlib mostly-compressed (or mostly-noisy) data, the final result can be upwards of 10% bigger than the original data. The header is 12 bytes.

File: CommandLine/emake/Proto2ES.cpp [hunk 2]
```diff
@@ -237,13 +237,15 @@ std::string Actions2Code(const ::google::protobuf::RepeatedPtrField< buffers::re
...
     Bytef* outbytef=new Bytef[outsize];
 
     compress(outbytef,&outsize,(Bytef*)inbuffer,actualsize);
 
+    actualsize = outsize;
```
Comment (JoshDreamland) [inline CommandLine/emake/Proto2ES.cpp]: Aha.
